services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zigzag
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres    

  ### ➡️ Add MinIO (Storage)
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin     # Username (change if needed)
      MINIO_ROOT_PASSWORD: minioadmin # Password (change if needed)
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: ./zigzagmicroservices/user-service
    container_name: user_service
    depends_on:
      - postgres

  event-service:
    build: ./zigzagmicroservices/events-service
    container_name: events_service
    depends_on:
      - postgres

  media-service:
    build: ./zigzagmicroservices/media-service
    container_name: media_service
    ports:
      - "3032:3032"
    depends_on:
      minio:
        condition: service_healthy   

volumes:   # <-- move this to root level
  pgdata:
  minio_data: