services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zigzag
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres    

  user-service:
    build: ./zigzagmicroservices/user-service
    container_name: user_service
    depends_on:
      - postgres

  event-service:
    build: ./zigzagmicroservices/events-service
    container_name: events_service
    depends_on:
      - postgres

volumes:
  pgdata: