version: "3.8"

services:
  database:
    image: postgres
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: node-server
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@database:5432/mydatabase
    ports:
      - "5000:5000"

volumes:
  pgdata: